### PR TITLE
Issue #3 solve

### PR DESCRIPTION
**Pull request by AJ-54**
NOTE:
- Please fill out the template below 

## Did you read the instructions in the [README](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/README.md)?

> Y

## Have you read the instructions in [CONTRIBUTING](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/CONTRIBUTING.md)?

> Y

## Have you written this article by yourself? Have you taken inspiration from anywhere and then written it in your words?

Yes

### CODE REVIEW

**Comment by AJ-54** [comment]
@the-ethan-hunt Kindly review my PR
Thank you

**Comment by dhruvapte26** [comment]
Plagiarised. @AJ-54 please write the article on your own! :smile:

**Comment by AJ-54** [comment]
@the-ethan-hunt Created unplagiarized content file.

**Comment by dhruvapte26** [comment]
@AJ-54 some points for the article:

- I don't want the advantages of Bazel. I can easily look up on it in any Computer Science textbook. What this guide needs is why Bazel is preferred over other build automation softwares, citing examples.
- Steps on installing Bazel. Is the project open-sourced? If yes, you can include the project link.
- Plugins (if any) required by Bazel.

A simple test to think through:
Imagine you are a second year Computer Science student trying to get hold of this for an **an interview** for an internship; **not a 5 mark question on the end semester exam paper**. Do you think this article could be useful for you here? Try doing this and you will automatically see your mistakes!

**Pull request closed without merging**
